SELECT MEMBER_ID, MEMBER_NAME, GENDER,
DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d") as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' and TLNO is not null
GROUP BY DATE_OF_BIRTH
HAVING MONTH(DATE_OF_BIRTH) = 3 
ORDER BY MEMBER_ID
